/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Punch.glb -o Punch.jsx -k 
Author: RahulD (https://sketchfab.com/rahuld)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tata-punch-tropical-mist-cdf0bb23de104a388942096fea6359f7
Title: Tata Punch Tropical Mist
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Punch.glb')
  return (
    <group {...props} dispose={null}>
      <group name="USDRoot" scale={0.02}>
        <group name="Meshes" scale={100}>
          <mesh name="Mesh_005_prim39" geometry={nodes.Mesh_005_prim39.geometry} material={materials.EXT_NUMBERPLATE_LIGHT} />
          <mesh name="Mesh_005_prim34" geometry={nodes.Mesh_005_prim34.geometry} material={materials.EXT_ORVM_INDICATOR_GLOW} />
          <mesh name="Mesh_005_prim37" geometry={nodes.Mesh_005_prim37.geometry} material={materials.EXT_TRYE_GRIP} />
          <mesh name="Mesh_005_prim44" geometry={nodes.Mesh_005_prim44.geometry} material={materials.EXT_MATT_CHROME} />
          <mesh name="Mesh_005_prim21" geometry={nodes.Mesh_005_prim21.geometry} material={materials.INT_METER_SCREEN} />
          <mesh name="Mesh_005_prim20" geometry={nodes.Mesh_005_prim20.geometry} material={materials.EXT_BUMPER_PLASTIC} />
          <mesh name="Mesh_005_prim50" geometry={nodes.Mesh_005_prim50.geometry} material={materials.INT_SHINY_BLACK_PLASTIC} />
          <mesh name="Mesh_005_prim88" geometry={nodes.Mesh_005_prim88.geometry} material={materials.INT_SEAT_FABRIC_DARK} />
          <mesh name="Mesh_005_prim62" geometry={nodes.Mesh_005_prim62.geometry} material={materials.INT_STEERING_LEATHER} />
          <mesh name="Mesh_005_prim66" geometry={nodes.Mesh_005_prim66.geometry} material={materials.INT_RED_BUTTON} />
          <mesh name="Mesh_005_prim89" geometry={nodes.Mesh_005_prim89.geometry} material={materials.INT_SEAT_STITCHES} />
          <mesh name="Mesh_005_prim68" geometry={nodes.Mesh_005_prim68.geometry} material={materials.INT_SILVERCHROME} />
          <mesh name="Mesh_005_prim82" geometry={nodes.Mesh_005_prim82.geometry} material={materials.INT_AMT_STEERING_LEATHER} />
          <mesh name="Mesh_005_prim85" geometry={nodes.Mesh_005_prim85.geometry} material={materials.EXT_COLORBODY} />
          <mesh name="Mesh_005_prim86" geometry={nodes.Mesh_005_prim86.geometry} material={materials.INT_DASH_PLASTIC} />
          <mesh name="Mesh_005_prim75" geometry={nodes.Mesh_005_prim75.geometry} material={materials.EXT_NUMBER_PLATE} />
          <mesh name="Mesh_005_prim80" geometry={nodes.Mesh_005_prim80.geometry} material={materials.INT_AMT_DECALS} />
          <mesh name="Mesh_005_prim64" geometry={nodes.Mesh_005_prim64.geometry} material={materials.INT_PLASTIC_MECHA} />
          <mesh name="Mesh_005_prim65" geometry={nodes.Mesh_005_prim65.geometry} material={materials.INT_BLACK_METAL} />
          <mesh name="Mesh_005_prim19" geometry={nodes.Mesh_005_prim19.geometry} material={materials.EXT_DOOR_LOCK_CHROME} />
          <mesh name="Mesh_005_prim13" geometry={nodes.Mesh_005_prim13.geometry} material={materials.EXT_WINDOW_GLASS} />
          <mesh name="Mesh_005_prim25" geometry={nodes.Mesh_005_prim25.geometry} material={materials.EXT_PROJECTOR_LIGHT_GLOW} />
          <mesh name="Mesh_005_prim51" geometry={nodes.Mesh_005_prim51.geometry} material={materials.INT_AC_VENT_SURROUND} />
          <mesh name="Mesh_005_prim47" geometry={nodes.Mesh_005_prim47.geometry} material={materials.EXT_PLASTIC_STICKER} />
          <mesh name="Mesh_005_prim10" geometry={nodes.Mesh_005_prim10.geometry} material={materials.EXT_STRIPE_PATTERN} />
          <mesh name="Mesh_005_prim9" geometry={nodes.Mesh_005_prim9.geometry} material={materials.EXT_PLASTIC_SHINY_BLACK} />
          <mesh name="Mesh_005_prim12" geometry={nodes.Mesh_005_prim12.geometry} material={materials.EXT_TAILIGHT_STOP_GLOW} />
          <mesh name="Mesh_005_prim14" geometry={nodes.Mesh_005_prim14.geometry} material={materials.EXT_TAILLIGHT_DETAIL_RED_GLOW} />
          <mesh name="Mesh_005_prim60" geometry={nodes.Mesh_005_prim60.geometry} material={materials.INT_KNURL} />
          <mesh name="Mesh_005_prim43" geometry={nodes.Mesh_005_prim43.geometry} material={materials.EXT_TAILLIGHT_RED_DETAIL} />
          <mesh name="Mesh_005_prim41" geometry={nodes.Mesh_005_prim41.geometry} material={materials.EXT_DEFOGGER} />
          <mesh name="Mesh_005_prim22" geometry={nodes.Mesh_005_prim22.geometry} material={materials.INT_BOTTOM_SPEAKERS} />
          <mesh name="Mesh_005_prim42" geometry={nodes.Mesh_005_prim42.geometry} material={materials.EXT_TAILLIGHT_RED_GLASS} />
          <mesh name="Mesh_005_prim18" geometry={nodes.Mesh_005_prim18.geometry} material={materials.EXT_REAR_BOTTOM_STOPLIGHT} />
          <mesh name="Mesh_005_prim17" geometry={nodes.Mesh_005_prim17.geometry} material={materials.EXT_TAILLIGHT_LIGHT_GUIDE_GLOW} />
          <mesh name="Mesh_005_prim16" geometry={nodes.Mesh_005_prim16.geometry} material={materials.EXT_TAILLIGHT_DETAIL} />
          <mesh name="Mesh_005_prim56" geometry={nodes.Mesh_005_prim56.geometry} material={materials.INT_PLASTIC_MATT} />
          <mesh name="Mesh_005_prim57" geometry={nodes.Mesh_005_prim57.geometry} material={materials.INT_DASH_FABRIC} />
          <mesh name="Mesh_005_prim59" geometry={nodes.Mesh_005_prim59.geometry} material={materials.INT_BUTTON_PLASTIC} />
          <mesh name="Mesh_005_prim70" geometry={nodes.Mesh_005_prim70.geometry} material={materials.INT_DASH_TRIMS} />
          <mesh name="Mesh_005_prim55" geometry={nodes.Mesh_005_prim55.geometry} material={materials.INT_MATT_METAL} />
          <mesh name="Mesh_005_prim67" geometry={nodes.Mesh_005_prim67.geometry} material={materials.INT_PLASTIC_MATT_2} />
          <mesh name="Mesh_005_prim71" geometry={nodes.Mesh_005_prim71.geometry} material={materials.INT_BEIGE_PLASTIC_NO_AO} />
          <mesh name="Mesh_005_prim26" geometry={nodes.Mesh_005_prim26.geometry} material={materials.EXT_DRL_LIGHT_GLOW} />
          <mesh name="Mesh_005_prim7" geometry={nodes.Mesh_005_prim7.geometry} material={materials.EXT_TAILLIGHT_GLASS} />
          <mesh name="Mesh_005_prim36" geometry={nodes.Mesh_005_prim36.geometry} material={materials.EXT_TYRE_SIDE} />
          <mesh name="Mesh_005_prim8" geometry={nodes.Mesh_005_prim8.geometry} material={materials.EXT_RED_CHROME} />
          <mesh name="Mesh_005_prim28" geometry={nodes.Mesh_005_prim28.geometry} material={materials.EXT_FOGLIGHT_GLASS} />
          <mesh name="Mesh_005_prim5" geometry={nodes.Mesh_005_prim5.geometry} material={materials.EXT_PIANO_BLACK} />
          <mesh name="Mesh_005_prim32" geometry={nodes.Mesh_005_prim32.geometry} material={materials.INT_STEERING_STITCH} />
          <mesh name="Mesh_005_prim31" geometry={nodes.Mesh_005_prim31.geometry} material={materials.INT_LIGHTS} />
          <mesh name="Mesh_005_prim2" geometry={nodes.Mesh_005_prim2.geometry} material={materials.INT_CARPET} />
          <mesh name="Mesh_005_prim0" geometry={nodes.Mesh_005_prim0.geometry} material={materials.INT_COLORBODY} />
          <mesh name="Mesh_005_prim1" geometry={nodes.Mesh_005_prim1.geometry} material={materials.INT_METAL_BLACK} />
          <mesh name="Mesh_005_prim54" geometry={nodes.Mesh_005_prim54.geometry} material={materials.INT_RUBBER} />
          <mesh name="Mesh_005_prim72" geometry={nodes.Mesh_005_prim72.geometry} material={materials.INT_ROOF} />
          <mesh name="Mesh_005_prim38" geometry={nodes.Mesh_005_prim38.geometry} material={materials.EXT_TOP_STOPLIGHT} />
          <mesh name="Mesh_005_prim53" geometry={nodes.Mesh_005_prim53.geometry} material={materials.INT_DECALS} />
          <mesh name="Mesh_005_prim45" geometry={nodes.Mesh_005_prim45.geometry} material={materials.EXT_BRAKEMETAL} />
          <mesh name="Mesh_005_prim27" geometry={nodes.Mesh_005_prim27.geometry} material={materials.EXT_FRONT_INDICATOR_GLOW} />
          <mesh name="Mesh_005_prim46" geometry={nodes.Mesh_005_prim46.geometry} material={materials.EXT_PLASTIC_MATT} />
          <mesh name="Mesh_005_prim81" geometry={nodes.Mesh_005_prim81.geometry} material={materials.INT_AMT_DOTTED_PLASTIC} />
          <mesh name="Mesh_005_prim30" geometry={nodes.Mesh_005_prim30.geometry} material={materials.EXT_COLORBODY_2} />
          <mesh name="Mesh_005_prim90" geometry={nodes.Mesh_005_prim90.geometry} material={materials.EXT_TYRE_RIM} />
          <mesh name="Mesh_005_prim58" geometry={nodes.Mesh_005_prim58.geometry} material={materials.INT_DASH_BRUSHED_PLASTIC} />
          <mesh name="Mesh_005_prim63" geometry={nodes.Mesh_005_prim63.geometry} material={materials.INT_BEIGE_PLASTIC} />
          <mesh name="Mesh_005_prim69" geometry={nodes.Mesh_005_prim69.geometry} material={materials.INT_SEAT_BELT} />
          <mesh name="Mesh_005_prim73" geometry={nodes.Mesh_005_prim73.geometry} material={materials.INT_INFO_SCREEN} />
          <mesh name="Mesh_005_prim74" geometry={nodes.Mesh_005_prim74.geometry} material={materials.INT_TOP_SPEAKERS} />
          <mesh name="Mesh_005_prim87" geometry={nodes.Mesh_005_prim87.geometry} material={materials.INT_SEAT_DESIGN} />
          <mesh name="Mesh_005_prim52" geometry={nodes.Mesh_005_prim52.geometry} material={materials.INT_CHROME} />
          <mesh name="Mesh_005_prim15" geometry={nodes.Mesh_005_prim15.geometry} material={materials.GAPFILL} />
          <mesh name="Mesh_005_prim61" geometry={nodes.Mesh_005_prim61.geometry} material={materials.INT_PIANO_BLACK} />
          <mesh name="Mesh_005_prim4" geometry={nodes.Mesh_005_prim4.geometry} material={materials.EXT_CHROME} />
          <mesh name="Mesh_005_prim3" geometry={nodes.Mesh_005_prim3.geometry} material={materials.INT_PLASTIC} />
          <mesh name="Mesh_005_prim77" geometry={nodes.Mesh_005_prim77.geometry} material={materials.INT_PLASTIC} />
          <mesh name="Mesh_005_prim6" geometry={nodes.Mesh_005_prim6.geometry} material={materials.EXT_DRL_GLASS} />
          <mesh name="Mesh_005_prim40" geometry={nodes.Mesh_005_prim40.geometry} material={materials.EXT_PLASTIC_2} />
          <mesh name="Mesh_005_prim48" geometry={nodes.Mesh_005_prim48.geometry} material={materials.EXT_PLASTIC_2} />
          <mesh name="Mesh_005_prim33" geometry={nodes.Mesh_005_prim33.geometry} material={materials.EXT_MIRROR} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Punch.glb')
