/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Safari.glb -o Safari.jsx -k 
Author: BHP3D (https://sketchfab.com/BHP3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2021-tata-safari-3051714dba91468f9d3f4f15305c2541
Title: 2021 Tata Safari
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Safari.glb')
  return (
    <group {...props} dispose={null}>
      <group name="safarifbx" scale={0.015}>
        <group name="safari" position={[0, 110.451, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group name="wheel_dummy" position={[0.905, 1.737, -0.678]}>
            <group name="wheel_fr" position={[0.001, 0, 0]}>
              <mesh name="wheel_fr_chassis1_0" geometry={nodes.wheel_fr_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh name="wheel_fr_chassis4_0" geometry={nodes.wheel_fr_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh name="wheel_fr_chassis0_0" geometry={nodes.wheel_fr_chassis0_0.geometry} material={materials['chassis.0']} />
              <mesh name="wheel_fr_primary_0" geometry={nodes.wheel_fr_primary_0.geometry} material={materials.primary} />
              <mesh name="wheel_fr_safari_b_032_0" geometry={nodes.wheel_fr_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
              <mesh name="wheel_fr_wheel_rf5_0" geometry={nodes.wheel_fr_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <group name="wheel_rr" position={[0.001, -3.108, 0]}>
              <mesh name="wheel_rr_chassis0_0" geometry={nodes.wheel_rr_chassis0_0.geometry} material={materials['chassis.0']} />
              <mesh name="wheel_rr_chassis1_0" geometry={nodes.wheel_rr_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh name="wheel_rr_primary_0" geometry={nodes.wheel_rr_primary_0.geometry} material={materials.primary} />
              <mesh name="wheel_rr_safari_b_032_0" geometry={nodes.wheel_rr_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            </group>
            <group name="wheel_rl" position={[-1.81, -3.108, 0]} scale={[-1, 1, 1]}>
              <mesh name="wheel_rl_chassis0_0" geometry={nodes.wheel_rl_chassis0_0.geometry} material={materials['chassis.0']} />
              <mesh name="wheel_rl_chassis1_0" geometry={nodes.wheel_rl_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh name="wheel_rl_primary_0" geometry={nodes.wheel_rl_primary_0.geometry} material={materials.primary} />
              <mesh name="wheel_rl_safari_b_032_0" geometry={nodes.wheel_rl_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            </group>
            <group name="wheel_fl" position={[-1.81, 0, 0]} scale={[-1, 1, 1]}>
              <mesh name="wheel_fl_chassis1_0" geometry={nodes.wheel_fl_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh name="wheel_fl_chassis4_0" geometry={nodes.wheel_fl_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh name="wheel_fl_chassis0_0" geometry={nodes.wheel_fl_chassis0_0.geometry} material={materials['chassis.0']} />
              <mesh name="wheel_fl_primary_0" geometry={nodes.wheel_fl_primary_0.geometry} material={materials.primary} />
              <mesh name="wheel_fl_safari_b_032_0" geometry={nodes.wheel_fl_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
              <mesh name="wheel_fl_wheel_rf5_0" geometry={nodes.wheel_fl_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
          </group>
          <group name="hub_lb" position={[0, 3.675, -1.138]}>
            <mesh name="hub_lb_chassis1_0" geometry={nodes.hub_lb_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="hub_lb_chassis4_0" geometry={nodes.hub_lb_chassis4_0.geometry} material={materials['chassis.4']} />
          </group>
          <group name="hub_rb" position={[0, 3.675, -1.138]}>
            <mesh name="hub_rb_chassis1_0" geometry={nodes.hub_rb_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="hub_rb_chassis4_0" geometry={nodes.hub_rb_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="hub_rb_wheel_rf5_0" geometry={nodes.hub_rb_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
          </group>
          <group name="chassis" position={[0, 3.675, -1.138]}>
            <mesh name="chassis_chassis5_0" geometry={nodes.chassis_chassis5_0.geometry} material={materials['chassis.5']} />
            <mesh name="chassis_chassis1_0" geometry={nodes.chassis_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="chassis_chassis4_0" geometry={nodes.chassis_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="chassis_chassis3_0" geometry={nodes.chassis_chassis3_0.geometry} material={materials['chassis.3']} />
            <mesh name="chassis_chassis0_0" geometry={nodes.chassis_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="chassis_chassis2_0" geometry={nodes.chassis_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="bodyshell_primary_0" geometry={nodes.bodyshell_primary_0.geometry} material={materials.primary} />
            <mesh name="safari_b_01_chassis1_0" geometry={nodes.safari_b_01_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_01_chassis0_0" geometry={nodes.safari_b_01_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_01_safari_b_032_0" geometry={nodes.safari_b_01_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_02_chassis0_0" geometry={nodes.safari_b_02_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_02_chassis1_0" geometry={nodes.safari_b_02_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_03_chassis0_0" geometry={nodes.safari_b_03_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_03_safari_b_031_0" geometry={nodes.safari_b_03_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="safari_b_03_safari_b_032_0" geometry={nodes.safari_b_03_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_03_chassis1_0" geometry={nodes.safari_b_03_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_04_safari_b_040_0" geometry={nodes.safari_b_04_safari_b_040_0.geometry} material={materials['safari_b_04.0']} />
            <mesh name="safari_b_06_chassis0_0" geometry={nodes.safari_b_06_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_06_primary_0" geometry={nodes.safari_b_06_primary_0.geometry} material={materials.primary} />
            <mesh name="safari_b_06_safari_b_031_0" geometry={nodes.safari_b_06_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="safari_b_06_chassis1_0" geometry={nodes.safari_b_06_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_06_safari_b_032_0" geometry={nodes.safari_b_06_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_07_safari_b_032_0" geometry={nodes.safari_b_07_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_07_safari_b_072_0" geometry={nodes.safari_b_07_safari_b_072_0.geometry} material={materials['safari_b_07.2']} />
            <mesh name="safari_b_07_safari_b_070_0" geometry={nodes.safari_b_07_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="safari_b_07_chassis0_0" geometry={nodes.safari_b_07_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_07_chassis1_0" geometry={nodes.safari_b_07_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_07_safari_b_102_0" geometry={nodes.safari_b_07_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_b_08_chassis1_0" geometry={nodes.safari_b_08_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_08_chassis0_0" geometry={nodes.safari_b_08_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_08_safari_b_032_0" geometry={nodes.safari_b_08_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_08_safari_b_070_0" geometry={nodes.safari_b_08_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="safari_b_08_safari_b_080_0" geometry={nodes.safari_b_08_safari_b_080_0.geometry} material={materials['safari_b_08.0']} />
            <mesh name="safari_b_08_safari_b_102_0" geometry={nodes.safari_b_08_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_b_09_chassis0_0" geometry={nodes.safari_b_09_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_09_safari_b_031_0" geometry={nodes.safari_b_09_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="safari_b_09_chassis1_0" geometry={nodes.safari_b_09_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_09_safari_b_070_0" geometry={nodes.safari_b_09_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="safari_b_09_safari_b_102_0" geometry={nodes.safari_b_09_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_b_09_safari_b_114_0" geometry={nodes.safari_b_09_safari_b_114_0.geometry} material={materials['safari_b_11.4']} />
            <mesh name="safari_b_09_safari_b_032_0" geometry={nodes.safari_b_09_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_09_safari_b_090_0" geometry={nodes.safari_b_09_safari_b_090_0.geometry} material={materials['safari_b_09.0']} />
            <mesh name="safari_b_10_chassis0_0" geometry={nodes.safari_b_10_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_10_chassis2_0" geometry={nodes.safari_b_10_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="safari_b_10_safari_b_032_0" geometry={nodes.safari_b_10_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_10_safari_b_100_0" geometry={nodes.safari_b_10_safari_b_100_0.geometry} material={materials['safari_b_10.0']} />
            <mesh name="safari_b_10_safari_b_101_0" geometry={nodes.safari_b_10_safari_b_101_0.geometry} material={materials['safari_b_10.1']} />
            <mesh name="safari_b_10_safari_b_102_0" geometry={nodes.safari_b_10_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_b_10_safari_b_106_0" geometry={nodes.safari_b_10_safari_b_106_0.geometry} material={materials['safari_b_10.6']} />
            <mesh name="safari_b_11_chassis1_0" geometry={nodes.safari_b_11_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_b_11_chassis0_0" geometry={nodes.safari_b_11_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_11_safari_b_032_0" geometry={nodes.safari_b_11_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_11_safari_b_102_0" geometry={nodes.safari_b_11_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_b_11_safari_b_114_0" geometry={nodes.safari_b_11_safari_b_114_0.geometry} material={materials['safari_b_11.4']} />
            <mesh name="safari_b_11_safari_b_031_0" geometry={nodes.safari_b_11_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="safari_b_11_safari_b_106_0" geometry={nodes.safari_b_11_safari_b_106_0.geometry} material={materials['safari_b_10.6']} />
            <mesh name="safari_b_11_safari_b_090_0" geometry={nodes.safari_b_11_safari_b_090_0.geometry} material={materials['safari_b_09.0']} />
            <mesh name="safari_b_12_chassis0_0" geometry={nodes.safari_b_12_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_b_12_safari_b_032_0" geometry={nodes.safari_b_12_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_b_12_safari_b_122_0" geometry={nodes.safari_b_12_safari_b_122_0.geometry} material={materials['safari_b_12.2']} />
            <mesh name="safari_b_12_chassis1_0" geometry={nodes.safari_b_12_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="dashboard_chassis0_0" geometry={nodes.dashboard_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="dashboard_chassis2_0" geometry={nodes.dashboard_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="dashboard_safari_b_031_0" geometry={nodes.dashboard_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="dashboard_safari_b_032_0" geometry={nodes.dashboard_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="dashboard_safari_b_070_0" geometry={nodes.dashboard_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="dashboard_safari_b_102_0" geometry={nodes.dashboard_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="dashboard_safari_b_114_0" geometry={nodes.dashboard_safari_b_114_0.geometry} material={materials['safari_b_11.4']} />
            <mesh name="dashboard_dashboard6_0" geometry={nodes.dashboard_dashboard6_0.geometry} material={materials['dashboard.6']} />
            <mesh name="dashboard_dashboard7_0" geometry={nodes.dashboard_dashboard7_0.geometry} material={materials['dashboard.7']} />
            <mesh name="dashboard_chassis1_0" geometry={nodes.dashboard_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="dashboard_back_chassis1_0" geometry={nodes.dashboard_back_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="dashboard_back_safari_b_101_0" geometry={nodes.dashboard_back_safari_b_101_0.geometry} material={materials['safari_b_10.1']} />
            <mesh name="dashboard001_glass_0" geometry={nodes.dashboard001_glass_0.geometry} material={materials.glass} />
            <mesh name="steeringwheel_chassis0_0" geometry={nodes.steeringwheel_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="steeringwheel_safari_b_032_0" geometry={nodes.steeringwheel_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="steeringwheel_safari_b_070_0" geometry={nodes.steeringwheel_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="steeringwheel_chassis2_0" geometry={nodes.steeringwheel_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="steeringwheel_safari_b_102_0" geometry={nodes.steeringwheel_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="indicator_lights_safari_b_122_0" geometry={nodes.indicator_lights_safari_b_122_0.geometry} material={materials['safari_b_12.2']} />
            <mesh name="tailight_right_rear_light_0" geometry={nodes.tailight_right_rear_light_0.geometry} material={materials.right_rear_light} />
            <mesh name="taillight_b_glass_glass001_0" geometry={nodes.taillight_b_glass_glass001_0.geometry} material={materials['glass.001']} />
            <mesh name="sunroof_chassis3_0" geometry={nodes.sunroof_chassis3_0.geometry} material={materials['chassis.3']} />
            <mesh name="sunroof_chassis0_0" geometry={nodes.sunroof_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="sunroof_safari_b_031_0" geometry={nodes.sunroof_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="sunroof_safari_b_032_0" geometry={nodes.sunroof_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="sunroof_safari_b_102_0" geometry={nodes.sunroof_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="sunroof_safari_b_122_0" geometry={nodes.sunroof_safari_b_122_0.geometry} material={materials['safari_b_12.2']} />
            <mesh name="sunroof_safari_b_114_0" geometry={nodes.sunroof_safari_b_114_0.geometry} material={materials['safari_b_11.4']} />
            <mesh name="sunroof_chassis1_0" geometry={nodes.sunroof_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="sunroof_chassis2_0" geometry={nodes.sunroof_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="safari_i_backseats_chassis0_0" geometry={nodes.safari_i_backseats_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_i_backseats_safari_b_102_0" geometry={nodes.safari_i_backseats_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_i_backseats_safari_b_106_0" geometry={nodes.safari_i_backseats_safari_b_106_0.geometry} material={materials['safari_b_10.6']} />
            <mesh name="safari_i_backseats_safari_b_090_0" geometry={nodes.safari_i_backseats_safari_b_090_0.geometry} material={materials['safari_b_09.0']} />
            <mesh name="safari_i_middleseats_chassis5_0" geometry={nodes.safari_i_middleseats_chassis5_0.geometry} material={materials['chassis.5']} />
            <mesh name="safari_i_middleseats_chassis1_0" geometry={nodes.safari_i_middleseats_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_i_middleseats_chassis4_0" geometry={nodes.safari_i_middleseats_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="safari_i_middleseats_chassis3_0" geometry={nodes.safari_i_middleseats_chassis3_0.geometry} material={materials['chassis.3']} />
            <mesh name="safari_i_middleseats_chassis0_0" geometry={nodes.safari_i_middleseats_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_i_middleseats_safari_b_102_0" geometry={nodes.safari_i_middleseats_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_i_middleseats_safari_b_031_0" geometry={nodes.safari_i_middleseats_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="headlights_led_right_front_light_0" geometry={nodes.headlights_led_right_front_light_0.geometry} material={materials.right_front_light} />
            <mesh name="headlight_glass_glass_0" geometry={nodes.headlight_glass_glass_0.geometry} material={materials.glass} />
            <mesh name="safari_t_sunroof_chassis1_0" geometry={nodes.safari_t_sunroof_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_t_sunroof_chassis0_0" geometry={nodes.safari_t_sunroof_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_t_sunroof_safari_b_032_0" geometry={nodes.safari_t_sunroof_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="sunroof_glass_glass_0" geometry={nodes.sunroof_glass_glass_0.geometry} material={materials.glass} />
            <mesh name="sunroof_glass_glass002_0" geometry={nodes.sunroof_glass_glass002_0.geometry} material={materials['glass.002']} />
            <mesh name="safari_bo_lights_led_chassis0_0" geometry={nodes.safari_bo_lights_led_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_bo_lights_led_right_front_light_0" geometry={nodes.safari_bo_lights_led_right_front_light_0.geometry} material={materials.right_front_light} />
            <mesh name="safari_bo_lights_chassis0_0" geometry={nodes.safari_bo_lights_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="safari_bo_lights_safari_b_031_0" geometry={nodes.safari_bo_lights_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="safari_bo_lights_safari_b_032_0" geometry={nodes.safari_bo_lights_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="safari_bo_lights_chassis1_0" geometry={nodes.safari_bo_lights_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="safari_bo_lights_glass_glass_0" geometry={nodes.safari_bo_lights_glass_glass_0.geometry} material={materials.glass} />
            <mesh name="lights_1_glass_0" geometry={nodes.lights_1_glass_0.geometry} material={materials.glass} />
            <mesh name="windscreen_glass_0" geometry={nodes.windscreen_glass_0.geometry} material={materials.glass} />
            <mesh name="window_rm_glass_0" geometry={nodes.window_rm_glass_0.geometry} material={materials.glass} />
            <mesh name="window_lm_glass_0" geometry={nodes.window_lm_glass_0.geometry} material={materials.glass} />
            <mesh name="tailight_glass_glass001_0" geometry={nodes.tailight_glass_glass001_0.geometry} material={materials['glass.001']} />
          </group>
          <group name="door_lf_dummy" position={[-0.983, 1.154, 0.027]}>
            <mesh name="door_lf_chassis4_0" geometry={nodes.door_lf_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="door_lf_chassis0_0" geometry={nodes.door_lf_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="door_lf_primary_0" geometry={nodes.door_lf_primary_0.geometry} material={materials.primary} />
            <mesh name="door_lf_safari_b_031_0" geometry={nodes.door_lf_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="door_lf_safari_b_032_0" geometry={nodes.door_lf_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="door_lf_safari_b_070_0" geometry={nodes.door_lf_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="door_lf_dashboard7_0" geometry={nodes.door_lf_dashboard7_0.geometry} material={materials['dashboard.7']} />
            <mesh name="door_lf_chassis1_0" geometry={nodes.door_lf_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="door_lf_safari_b_102_0" geometry={nodes.door_lf_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="door_lf_chassis2_0" geometry={nodes.door_lf_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="window_lf_glass_0" geometry={nodes.window_lf_glass_0.geometry} material={materials.glass} />
          </group>
          <group name="door_rf_dummy" position={[0.984, 1.155, 0.028]}>
            <mesh name="door_rf_chassis4_0" geometry={nodes.door_rf_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="door_rf_chassis0_0" geometry={nodes.door_rf_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="door_rf_safari_b_031_0" geometry={nodes.door_rf_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="door_rf_safari_b_032_0" geometry={nodes.door_rf_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="door_rf_safari_b_070_0" geometry={nodes.door_rf_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="door_rf_dashboard7_0" geometry={nodes.door_rf_dashboard7_0.geometry} material={materials['dashboard.7']} />
            <mesh name="door_rf_chassis1_0" geometry={nodes.door_rf_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="door_rf_safari_b_102_0" geometry={nodes.door_rf_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="door_rf_chassis2_0" geometry={nodes.door_rf_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="door_rf_primary_0" geometry={nodes.door_rf_primary_0.geometry} material={materials.primary} />
            <mesh name="window_rf_glass_0" geometry={nodes.window_rf_glass_0.geometry} material={materials.glass} />
          </group>
          <group name="door_lr_dummy" position={[-1.011, -0.081, 0.027]}>
            <mesh name="door_lr_chassis4_0" geometry={nodes.door_lr_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="door_lr_chassis2_0" geometry={nodes.door_lr_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="door_lr_primary_0" geometry={nodes.door_lr_primary_0.geometry} material={materials.primary} />
            <mesh name="door_lr_safari_b_031_0" geometry={nodes.door_lr_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="door_lr_safari_b_032_0" geometry={nodes.door_lr_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="door_lr_safari_b_070_0" geometry={nodes.door_lr_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="door_lr_chassis1_0" geometry={nodes.door_lr_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="door_lr_safari_b_102_0" geometry={nodes.door_lr_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="door_lr_chassis0_0" geometry={nodes.door_lr_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="window_lr_glass_0" geometry={nodes.window_lr_glass_0.geometry} material={materials.glass} />
          </group>
          <group name="boot_dummy" position={[0, -1.883, 0.896]}>
            <mesh name="boot_chassis0_0" geometry={nodes.boot_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="boot_safari_b_031_0" geometry={nodes.boot_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="boot_safari_b_114_0" geometry={nodes.boot_safari_b_114_0.geometry} material={materials['safari_b_11.4']} />
            <mesh name="boot_boot0_0" geometry={nodes.boot_boot0_0.geometry} material={materials['boot.0']} />
            <mesh name="boot_chassis1_0" geometry={nodes.boot_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="boot_primary_0" geometry={nodes.boot_primary_0.geometry} material={materials.primary} />
            <mesh name="boot_safari_b_032_0" geometry={nodes.boot_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="boot_safari_b_102_0" geometry={nodes.boot_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="safari_boot_grills_safari_boot_grills0_0" geometry={nodes.safari_boot_grills_safari_boot_grills0_0.geometry} material={materials['safari_boot_grills.0']} />
            <mesh name="safari_boot_lights_led_right_rear_light_0" geometry={nodes.safari_boot_lights_led_right_rear_light_0.geometry} material={materials.right_rear_light} />
            <mesh name="safari_boot_windowscreen_glass_0" geometry={nodes.safari_boot_windowscreen_glass_0.geometry} material={materials.glass} />
            <mesh name="boot_light_glass_glass001_0" geometry={nodes.boot_light_glass_glass001_0.geometry} material={materials['glass.001']} />
          </group>
          <group name="door_rr_dummy" position={[1.011, -0.082, 0.028]}>
            <mesh name="door_rr_chassis4_0" geometry={nodes.door_rr_chassis4_0.geometry} material={materials['chassis.4']} />
            <mesh name="door_rr_chassis0_0" geometry={nodes.door_rr_chassis0_0.geometry} material={materials['chassis.0']} />
            <mesh name="door_rr_chassis2_0" geometry={nodes.door_rr_chassis2_0.geometry} material={materials['chassis.2']} />
            <mesh name="door_rr_primary_0" geometry={nodes.door_rr_primary_0.geometry} material={materials.primary} />
            <mesh name="door_rr_safari_b_031_0" geometry={nodes.door_rr_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="door_rr_safari_b_032_0" geometry={nodes.door_rr_safari_b_032_0.geometry} material={materials['safari_b_03.2']} />
            <mesh name="door_rr_safari_b_070_0" geometry={nodes.door_rr_safari_b_070_0.geometry} material={materials['safari_b_07.0']} />
            <mesh name="door_rr_chassis1_0" geometry={nodes.door_rr_chassis1_0.geometry} material={materials['chassis.1']} />
            <mesh name="door_rr_safari_b_102_0" geometry={nodes.door_rr_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
            <mesh name="window_rr_glass_0" geometry={nodes.window_rr_glass_0.geometry} material={materials.glass} />
          </group>
          <group name="chassis001" position={[0, 3.675, -1.138]}>
            <mesh name="chassis001_safari_b_031_0" geometry={nodes.chassis001_safari_b_031_0.geometry} material={materials['safari_b_03.1']} />
            <mesh name="chassis001_safari_b_102_0" geometry={nodes.chassis001_safari_b_102_0.geometry} material={materials['safari_b_10.2']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Safari.glb')
